language: java
jdk:
- openjdk10
dist: xenial
services:
- docker
env:
  global:
  - secure: Cx6z/6gnI3cYM3L5iUI8ySKUxLdrv+isaOH7J/hPkJR+3RHKBJOCihurbyw+mV+jFEK6iK4/MFyMuTxkDj4XNxT6zGv6ZZNVBtb/Fl/88N9t9xBJmkYXLNrBbWtFdpjjP5HpmTbFibl/UE5vh8KntJhRnlKZrGAn6TwPui4PbRrft9UQQd4TuujyOC6qknR2okclwJ+o7TbXv0GrnoKFEKBQAt1Vt0PrGF2Hgxdaenmo/P15zZjFnQj1nat5AnpXdXIKZxoIp+XzwO5lTVRSUd7pshZrP9pRPOhYLmA6iDffG0XPAe7wegg7i27mTEVLrxRBnIvZMRhbPIY8gvxKdSYIxhqDd4x2OHhWlik74I9WMNI6/EKCQ2vAhiBqDbuV0S14Pu1UYTX8tITQ+quCHNMM73obSDXW/y7ZOuUt/kuY+dpAzmE+IOtmQ/63XU6/75fWzGb49Wp9znD/fQ72yqxF/plS/dv7brbpED3jXwMSTEqZy8uXQ8KqgJFbKEUFtQq4uO25u3f3fP+7+zwUqGR/wyxtNoYiWGmXIxe9rp02GLFprVwo3RtxLbTtU+bxDiHUCzGzBZ2qbFivkVjb/B/n0vv9o5Jss7oNfpj4jtWrw7tTizw+tBISXHQ+Fx60PILtPF2pi0a8RvSwsyw8ghA5AohtGJqLRsm0kTeDlO4=
  - secure: mIgED4XjvdvE3QoXQGZW0bVWzgnzomaudk5gNjz+xOwPegrfV6/vUYXtTGkaWGTswLAkvM9UVleWyCzfYY3RVJD+Ws504qwvcjPM2t+IYvAi8uOAZJPWAsnJhqlJnFdu6PNHIVfRbHKUaTmOr2+ttj/ixCK7Q1I9H8ZtypvdAkyrQ3xMD1x/5uZE6/iqbNywsvSKqOw1g7dF12r1Ts6DDBDT/WRgw4HQZqHayJZNE225+2Cf1VcJtTcuq3HMgKz1MHw2aozoxISaIIqx8XcGGA6L30yyavffzIE8uVNVJTTL0I0Elv/YsODDYogT/nsF9UEbjYNPSlWRSyoFVd5/KyUYd8JFQXeK4OR9KCe9J3IVfScuc+hL5UgkUJrjBg/V6hxnlDhZWHZNtig3YMaiF+JbcOch+xqugX2EbBLO4K557BBzHZJgPKe2KGM4WkFgaiLjp0GU+c9UK1sFnRfyxfZLrkrRT49w46fPZhT7A2yX+KbIhtMCPv4Ljw2Z9AMmjCyZOONtB4nYTzqHl3pzsvT+QWuQE6kPNchbLoLbtf3VoghcQzG4IRFPKKla8znw1mUWXOh0sOiev1YFQxRL2awdjumFzFkJIIxsTID/cjlphCh/vi62tl+bFL81Z5to0XXbFEzEiNclXyFWYhAPpkyGxU7KHj5DUzJTVfkVYro=
  - secure: Q+gii1axv+2o9e+BPPOov1yKtu9/5QqvTeCC4xP8cjcF7uTk2siRcIP09WM5rb5dY0ofW9A0CMzGxAgB7W/vz3FpV+daqpBhWAbxDcUz1a3zfN4RMpbWfkW8MxENa7Lgy6bf8VZ+9kxQqyw6WzBkPbS7amkfxCN6XekWQF+ss5dZC+SjSX8riATFqdSH6cbcpZWibnF1O36AdpTR+gU5OuCNfjrGVlXrOxqncXrGdKLqcrOisjhw9fVCoPH3Opcso0kGQQPksGXaeL4zoXwDdqJCwC2BUgbKayOPTeQbtoOBYyPybIbh0Aev19R9fr9S6UAmwJ/981xZvVtXjYTP31V4uVecTjFH+ca8woNjDN9keFlUe/qRFeeXzFEOy/Dt+8Ul9aWDWGEv9grLJEqza9m/Jjrjec9z3gzER+Khn101H6hBHn9R64JV5c2EtHAjlTRRe89oh16z/5HO1JT1wtf/3OLrdQJrjtCCAFqP6qdtVdikg3tAmxIs6+isgKu2nnp2QhVjMCRfSm8x0cuWK5cRLoPGpUO12rahppJommQVYL9ljVPrRxYKKgPuUc2ySheYND2xzaj6Uiif+gLwvkUjDxdBcvpZ3USpLNEVWFUSKFZhkcQJ+SvsPZ/VfvrvWqeYfnqBxwVMRMYuAxdgD+zpEG/FxwOxWX2WxHOUzHY=
  - secure: Oa25yxtTNJAAw6AbiiJYctZ2ZeYKWBLejrDlGj0Tha7G+U1m6f5DSJaw/fF5zl0SdKHEHuwof3jIUXwvoHo26AQtiIUSRbV+5FH2JOJaJnxrrZ8OnIdBl9RHzqU8eKaimpyicm0F4cTaShzEQvr1hribCH/B65tOjTmnN127Vp6IZBo9GTSBCHNlienNU8wls1M3f8eXLpAXlDgOy22/o9gGodFZAaVkkwq73QK5GEPw0+fZ4okInOkAamA0NNQG1+D90Gg/9KpOwz26J2ARqHzt8iY4/6uGeImxMRrbBDxwYVWZfyjaVac6kACWNBjWIVFRVLgQkL4EXHoxyemtjzlflXCe5VnZROr/h5x8rly6/8WkpBsgmymlZ6qHKaKRNBsTSh3pTYZ27iQLsyAbNgfhv3JtdMKD1YHGSH88rUEtpDDtasdi4vFhAJlGohZQ/XPUvRUejMpspf6KYn5FyJG5p3J/rTZ7Z0Oj8qU/VUD7ZIj+D8egQcNpXnyhnE7l9/8etNwZ+Mj7DH9k58uiEuDUIOqbgSqT6tbGiik++jVFxDU9fCef/dHgVYLqYSBl9yPOp7OqVXTzSv3tgglGxEnviYwRNqVUtCV34krbvKgmkHyNsridqqFnicPksjl/EaEXEe/1j26xmZaxDzIgFdHjUfSAu+CYFR75v1isulw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - mysql-server
    - mysql-client
install: "/bin/true"
script:
- "./test"
before_deploy:
- openssl aes-256-cbc -K $encrypted_1f2efd262236_key -iv $encrypted_1f2efd262236_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script: "./deploy"
