apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: workflow2
  name: workflow2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: workflow2
  template:
    metadata:
      labels:
        run: workflow2
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/liveramp-eng-bdi/workflow2
        name: workflow2
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: workflowdb-creds
          mountPath: /apps/secrets/workflow_db
          readOnly: true
        - name: workflowui-creds
          mountPath: /apps/secrets/workflow_ui
          readOnly: true
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=liveramp-eng-bdi:us-central1:bdi-workflow-dbs=tcp:3306",
                  "-credential_file=/apps/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: cloudsql-credentials
          mountPath: /apps/secrets/cloudsql
          readOnly: true
      volumes:
      - name: workflowdb-creds
        secret:
          secretName: workflow2-workflowdb-config
      - name: workflowui-creds
        secret:
          secretName: workflow2-workflowui-config
      - name: cloudsql-credentials
        secret:
          secretName: workflow2-cloudsql-proxy-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: workflow2
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  selector:
    run: workflow2
  ports:
  - port: 80
    targetPort: 8080